package:
  name: roq-fix-config
  version: {{ GIT_DESCRIBE_TAG }}

source:
  git_url: ..

build:
  skip: true  # [not unix]
  number: {{ ROQ_BUILD_NUMBER if ROQ_BUILD_NUMBER is defined else GIT_DESCRIBE_NUMBER }}                                
  script_env:                                                                                                           
    - ROQ_BUILD_NUMBER                                                                                                  
    - ROQ_BUILD_TYPE                                                                                                    
    - CFLAGS=-O3
    - CPPFLAGS=-O3  # [linux]
    - CPPFLAGS=-O3 -D_LIBCPP_DISABLE_AVAILABILITY  # [osx]
  run_exports:                                                                                                          
    - {{ pin_subpackage('roq-fix-config', max_pin='x.x.x') }}

requirements:
  build:
    - {{ compiler('cxx') }}
    - clangdev
    - cmake
    - make
    - pkg-config
  host:
    - catch2
    - libabseil
    - nlohmann_json
    - roq-flags
    - roq-io
    - roq-oss-benchmark
    - roq-oss-tomlplusplus
    - roq-web

about:
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Roq's FIX config service
